name: Check Style

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codestyle:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check code style
        id: black-check
        run: |
          pip install black
          black --check src/

      - name: Format and push
        if: failure()
        id: format
        run: |
          pip install black
          black src/
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@github.com'
          git commit -am "Apply black codestyle" --allow-empty
          git push origin HEAD:${{ github.head_ref }}

  docker_image:
    name: Test build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: laurihuotari/images
          tags: type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64

  notify:
    runs-on: ubuntu-latest
    needs:
      - codestyle
      - docker_image
    if: failure()
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
