name: Check Style

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  autoblack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

        - name: autoblack_check
          id: black-check
          continue-on-error: true
          run: |
            pip install black
            black --check src/
  codestyle:
    if: jobs.autoblack != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
       - name: Format and push
         id: format
         run: |
           black src/
           git config --global user.name github-actions
           git config --global user.email '${GITHUB_ACTOR}@github.com'
           git commit -am "Apply black codestyle" --allow-empty
           git push

  notify:
    runs-on: ubuntu-latest
    needs:
      - autoblack
    if: ${{ failure() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}