name: Check Style

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  autoblack:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        run: pip install black

      - name: autoblack_check
        id: black-check
        continue-on-error: true
        run: black --check src/

      - name: autoblack
        if: steps.black-check.outcome != 'success'
        run: |
          black src/
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@github.com'
          git commit -am "Apply black codestyle" --allow-empty
          git push