name: Draft release

on:
  push:
    branches:
      - main

jobs:
  draft:
    name: Draft new release
    runs-on: ubuntu-latest
    steps:
      - name: Draft new release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
