name: Check style

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - '*'

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        name: Check code style
        run: |
          pip install \
          --disable-pip-version-check black
          black --check .
